#ifndef _HARD_DOZEU_H_
#define _HARD_DOZEU_H_
enum{
	DIRECTION_INPUT = 0,
	DIRECTION_OUTPUT,
	DIRECTION_INPUT_8BIT = 0,
	DIRECTION_OUTPUT_8BIT = 0xff,
};

enum{
	WAVEFORM_BANK_CPU_6502_HIGH = 0,
	WAVEFORM_BANK_CPU_FLASH_HIGH,
	WAVEFORM_BANK_PPU,
	WAVEFORM_BANK_CPU_6502_LOW,
	WAVEFORM_BANK_UNDEF = 123
};
enum{
	WAVEFORM_WAVE_READ_SINGLE = 0,
	WAVEFORM_WAVE_WRITE_SINGLE,
	WAVEFORM_WAVE_READ_MULTI,
	WAVEFORM_WAVE_WRITE_MULTI,
};	
#endif
