#ifndef _SYNTAX_H_
#define _SYNTAX_H_
#include "config.h"
#include "header.h"
enum script_opcode{
	SCRIPT_OPCODE_MAPPER,
	SCRIPT_OPCODE_MIRROR,
	SCRIPT_OPCODE_CPU_ROMSIZE,
	SCRIPT_OPCODE_CPU_RAMSIZE,
	SCRIPT_OPCODE_CPU_FLASHSIZE,
	SCRIPT_OPCODE_PPU_ROMSIZE,
	SCRIPT_OPCODE_PPU_FLASHSIZE,
	SCRIPT_OPCODE_DUMP_START,
	SCRIPT_OPCODE_CPU_COMMAND,
	SCRIPT_OPCODE_CPU_READ,
	SCRIPT_OPCODE_CPU_WRITE,
	SCRIPT_OPCODE_CPU_RAMRW,
	SCRIPT_OPCODE_CPU_PROGRAM,
	SCRIPT_OPCODE_PPU_COMMAND,
	SCRIPT_OPCODE_PPU_RAMFIND,
	SCRIPT_OPCODE_PPU_SRAMTEST,
	SCRIPT_OPCODE_PPU_READ,
	SCRIPT_OPCODE_PPU_WRITE,
	SCRIPT_OPCODE_PPU_PROGRAM,
	SCRIPT_OPCODE_STEP_START,
	SCRIPT_OPCODE_STEP_END,
	SCRIPT_OPCODE_DUMP_END,
	SCRIPT_OPCODE_COMMENT,
	SCRIPT_OPCODE_NUM
};
extern const char OPSTR_CPU_ROMSIZE[];
extern const char OPSTR_CPU_RAMSIZE[];
extern const char OPSTR_CPU_FLASHSIZE[];
extern const char OPSTR_PPU_ROMSIZE[];
extern const char OPSTR_PPU_FLASHSIZE[];
extern const char OPSTR_CPU_RAMRW[];
struct script;
int syntax_check(char **text, int text_num, struct script *s, int mode);
#endif
